### ISSUE TITLE
ip doesn't show up when link clicked

### ISSUE THREAD

**Issue by HangWithCmm** [Lucksi/Interceptor#1]
the ip does not show up when clicked

**Comment by Lucksi** [comment]
Hi Thank you for reporting this issue.
It should be fixed now, please let me know :)

**Comment by HangWithCmm** [comment]
it still doesn't work and now the link doesn't show up

**Comment by Lucksi** [comment]
Try now i should have fixed the link

**Comment by HangWithCmm** [comment]
Did you also fix the ip grabber because that still didnt work

**Comment by HangWithCmm** [comment]
it was working now it forever gets stuck on "GENERATING URL..."

**Comment by HangWithCmm** [comment]
Do you think you could make it so that it doesn’t shut down the link once one person clicks it thx

**Comment by Lucksi** [comment]
Sorry for the late response.. There could be some problems if I won't shutdown the link.
For example it may give some connection errors and the previous ip that has been registered in the txt file will be overwritten by the newer one.
I hope that I'm being clear with the explanation :)

**Comment by HangWithCmm** [comment]
I think you missed read what I said I meant can you make it so that you can use the link multiple times before it automatically shuts down

**Comment by Lucksi** [comment]
The answer is the same, the ngrok link that is created is connected to a single session
If you will you use the same link again you will lost all the information that you have gathered before

**Comment by HangWithCmm** [comment]
I know do you think you can make it just like a grabfiy were multiple people can click it?

**Comment by Lucksi** [comment]
I don't know because after a certain period of time the link won't work anymore by itself and I'm not really sure if it will even work because if too many people will click on the link. There might be a too many connection error and the link won't work anymore

**Comment by HangWithCmm** [comment]
After the link is clicked once it shows this
![Uploading F2E53683-64E3-42EF-BDED-F0FAF19ED855.jpeg…]()

**Comment by Lucksi** [comment]
Yes I know it is in order to avoid connection errors and by the way for the question that you asked before it depends.. Yes I can make it just like a grabify link but I don't know if the  same link could actually work multiple times.
